### ISSUE TITLE
No method for ForwardDiff.Dual

### ISSUE THREAD

**Issue by grahamas** [oscardssmith/BetterExp.jl#5]
Thanks for implementing this!  This error sorta confuses me.  I would have thought the AD would go through into the meat of your exp implementation.

```
ERROR: MethodError: no method matching exp(::ForwardDiff.Dual{ForwardDiff.Tag{TravelingWaveSimulationsPlotting.var"#loss#27"{TravelingWaveSimulationsPlotting.var"#sigmoid_fn#26"{Float64,Float64}},Float64},Float64,2})
You may have intended to import Base.exp
Closest candidates are:
  exp(::T) where T<:Float64 at /home/graham/.julia/packages/BetterExp/DaCOJ/src/exp.jl:108
  exp(::T) where T<:Float32 at /home/graham/.julia/packages/BetterExp/DaCOJ/src/exp.jl:131
```

**Comment by oscardssmith** [comment]
The reason this isn't working is that the function this defines is specialized to only work on Float32 and Float64. This happens because it uses lots of bitwise operations that don't make sense on more complicated types. Adding a fallback definition wouldn't be a bad idea, but I probably won't since Julia 1.6 will have this improvement already.

**Comment by oscardssmith** [comment]
I'm going to close this, since this package is no longer useful with master Julia.
